*This notebook contains a sketch and examples of an approach to calculating flux divergence, using a simple diffusion problem as an example.*

# Raster grid example: faces and cells

Let's suppose we want to create a diffusion model with a raster grid, in which we compute gradients in a field, then flux based on gradient, and finally divergence of flux. Start by creating a small raster grid:

In [141]:
from landlab import RasterModelGrid
import numpy as np

In [142]:
rg = RasterModelGrid(3, 4, 10.0)
z = rg.add_zeros('node', 'topographic__elevation')
rg.set_closed_boundaries_at_grid_edges(True, True, False, False)
#rg.set_closed_nodes([3, 7, 8, 9, 10, 11])

In [143]:
z[5] = 50.
z[6] = 36.
print(z)

[  0.   0.   0.   0.   0.  50.  36.   0.   0.   0.   0.   0.]


## Gradients at faces, net fluxes at cells

There are several ways we can go about running the model, and we're going to explore each in turn. Here are some of the factors at play. We have a field of elevation at *all* nodes---that's what we want to track. Some of those nodes, however, are boundary nodes, and should be held fixed (or manipulated independently). Some of the links are inactive. Only the core nodes are subject to change due to fluxes in and out. In any event, we can only really do a mass balance on a cell; a node is just a point. As to fluxes: these depend, of course, on the gradient in *z*. We can compute gradients on *links* or on *faces*. The two are nearly identical---both are gradients between values at the nodes on either side of a link---but they differ in array length. A calculation done on links is NL (number of links) long (17 in the case of a 3x4 grid); one done on faces is NF (number of faces) long (7 for a 3x4 grid). Note that the number of faces is equal to the number of *interior links*.

The upshot, then, is that we'll start with an example that calculates gradient on *faces*. Since LL at this writing doesn't have a face-gradient method (I don't think), we'll define one:

In [144]:
def calculate_gradients_at_faces(grid, node_values):
    """
    Given array of values at nodes, calculate gradients across corresponding cell faces.
    
    Notes
    -----
    - Requires 3 instances of fancy indexing
    - link_at_face is currently a method rather than a property
    """
    laf = grid.link_at_face
    gaf = (node_values[grid.node_at_link_head[laf]] - \
           node_values[grid.node_at_link_tail[laf]]) / grid.link_length[laf]
    return gaf

Let's test it. The gradient array should be:
`[5, 3.6, 5, -1.4, -3.6, -5, -3.6]`

In [145]:
grad_at_faces = calculate_gradients_at_faces(rg, z)
grad_at_faces

array([ 5. ,  3.6,  5. , -1.4, -3.6, -5. , -3.6])

So now we have an NF-long array of gradients. Let's make a unit flux out of this, by multiplying gradient by -1 (stuff flows down hill):

In [146]:
unit_flux_at_faces = -grad_at_faces
unit_flux_at_faces

array([-5. , -3.6, -5. ,  1.4,  3.6,  5. ,  3.6])

We might alternatively only want to calculate gradients and fluxes at *active faces*, which are faces crossed by an active link. How to get this?

In [147]:
rg.active_faces

array([0, 1, 2, 3])

The unit flux at active faces should be the same as `unit_flux_at_faces` but with 3 entries zeroed out:

In [148]:
unit_flux_at_active_faces = np.zeros(rg.number_of_faces)
unit_flux_at_active_faces[rg.active_faces] = unit_flux_at_faces[rg.active_faces]
unit_flux_at_active_faces

array([-5. , -3.6, -5. ,  1.4,  0. ,  0. ,  0. ])

### Net face fluxes at cells

Next, let's find the net face fluxes at cells. This is defined as the sum of total inflows and outflows. In order to do this, we need two data structures: *faces_at_cell* and *link_dirs_at_node*. The first is an M x N array of int that contains the IDs of faces at each cell, in counter-clockwise orientation starting with east (raster) or nearest CCW to east (others). Here M is the maximum number of links at a node, which is 4 for raster, 6 for hex, and arbitrary for Voronoi.

To get `faces_at_cell`, we first need to create `links_at_node` (and while we're at it, we'll also create `link_dirs_at_node`). That's done with this function:

In [149]:
def make_links_at_node_array_raster(grid):
    """Make array with links at each node
    
    Examples
    --------
    >>> from landlab import RasterModelGrid
    >>> rmg = RasterModelGrid(3, 4)
    >>> make_links_at_node_array_raster(rmg)
    >>> rmg.gt_links_at_node    
    array([[ 0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16, -1],
           [ 3,  4,  5,  6, 10, 11, 12, 13, -1, -1, -1, -1],
           [-1,  0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16],
           [-1, -1, -1, -1,  3,  4,  5,  6, 10, 11, 12, 13]], dtype=int32)
    >>> rmg.gt_link_dirs_at_node
    array([[-1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,  0],
           [-1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0],
           [ 0,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1],
           [ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1]], dtype=int8)
    """
    
    # Create arrays for link-at-node information
    grid.gt_links_at_node = -np.ones((4, grid.number_of_nodes), dtype=np.int32)
    grid.gt_link_dirs_at_node = np.zeros((4, grid.number_of_nodes), dtype=np.int8)
    grid.gt_active_link_dirs_at_node = np.zeros((4, grid.number_of_nodes), dtype=np.int8)
    grid.gt_num_links_at_node = np.zeros(grid.number_of_nodes, dtype=np.uint8)  # assume <256 links at any node
    grid.gt_num_active_links_at_node = np.zeros(grid.number_of_nodes, dtype=np.uint8)  # assume <256 links at any node

    num_links_per_row = (grid.number_of_node_columns * 2) - 1

    # Sweep over all links
    for lk in xrange(grid.number_of_links):

        # Find the orientation
        is_horiz = (lk % num_links_per_row) < (grid.number_of_node_columns - 1)

        # Find the IDs of the tail and head nodes
        t = grid.node_at_link_tail[lk]
        h = grid.node_at_link_head[lk]

        # If the link is horizontal, the index (row) in the links_at_node array
        # should be 0 (east) for the tail node, and 2 (west) for the head node.
        # If vertical, the index should be 1 (north) for the tail node and
        # 3 (south) for the head node.
        if is_horiz:
            tail_index = 0
            head_index = 2
        else:
            tail_index = 1
            head_index = 3

        # Add this link to the list for this node, set the direction (outgoing,
        # indicated by -1), and increment the number found so far
        grid.gt_links_at_node[tail_index][t] = lk
        grid.gt_links_at_node[head_index][h] = lk
        grid.gt_link_dirs_at_node[tail_index][t] = -1
        grid.gt_link_dirs_at_node[head_index][h] = 1
        grid.gt_num_links_at_node[h] += 1
        grid.gt_num_links_at_node[t] += 1


In our 3x4 raster grid, the links_at_node array should look like the following. There are N (# nodes) columns and four rows; each row represents a cardinal direction (east, north, west, and south). For example, node 5 is one of only two interior nodes; it is connected to links 8, 11, 7, and 4, on the east, north, west, and south sides, respectively. (Note that unstructured grids will not use cardinal directions, as illustrated later).

`array([[ 0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16, -1],
       [ 3,  4,  5,  6, 10, 11, 12, 13, -1, -1, -1, -1],
       [-1,  0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16],
       [-1, -1, -1, -1,  3,  4,  5,  6, 10, 11, 12, 13]], dtype=int32)`

In [150]:
make_links_at_node_array_raster(rg)
rg.gt_links_at_node

array([[ 0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16, -1],
       [ 3,  4,  5,  6, 10, 11, 12, 13, -1, -1, -1, -1],
       [-1,  0,  1,  2, -1,  7,  8,  9, -1, 14, 15, 16],
       [-1, -1, -1, -1,  3,  4,  5,  6, 10, 11, 12, 13]], dtype=int32)

The `link_dirs_at_node` array indicates the direction of each of a node's links relative to the node. For each link and node, an entry of 1 means that link is *entering* the node; in other words, the node is that link's *head*. An entry of -1 means that link is *leaving* the node; the node is that link's *tail*. An entry of zero means that there is no link at this position. For example, node 0 (lower-left corner) has outgoing links on the east and north, but no links on the west or south.

In [151]:
rg.gt_link_dirs_at_node

array([[-1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1,  0],
       [-1, -1, -1, -1, -1, -1, -1, -1,  0,  0,  0,  0],
       [ 0,  1,  1,  1,  0,  1,  1,  1,  0,  1,  1,  1],
       [ 0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1]], dtype=int8)

Before we can take the next step, we also need `faces_at_cell`: an M x NC array containing the face IDs at each cell, ordered CCW. The following function creates this. It's been expanded here to illustrate how it works:

In [152]:
def make_faces_at_cell(grid):
    max_num_faces = grid.gt_links_at_node.shape[0]
    grid.gt_faces_at_cell = np.zeros((max_num_faces, grid.number_of_cells), dtype=np.int)
    fal = grid.face_at_link
    print 'Face at link', fal
    nac = grid.node_at_cell
    print 'Node at cell:', nac
    for r in range(max_num_faces):
        lanr = grid.gt_links_at_node[r,nac]
        print 'Row', r, 'links at these nodes', lanr
        grid.gt_faces_at_cell[r,:] = fal[lanr]
        print 'Face', r, 'at these cells', fal[lanr]
    print grid.gt_faces_at_cell

In [153]:
make_faces_at_cell(rg)
rg.gt_faces_at_cell

Face at link [2147483647 2147483647 2147483647 2147483647          0          1
 2147483647          2          3          4 2147483647          5
          6 2147483647 2147483647 2147483647 2147483647]
Node at cell: [5 6]
Row 0 links at these nodes [8 9]
Face 0 at these cells [3 4]
Row 1 links at these nodes [11 12]
Face 1 at these cells [5 6]
Row 2 links at these nodes [7 8]
Face 2 at these cells [2 3]
Row 3 links at these nodes [4 5]
Face 3 at these cells [0 1]
[[3 4]
 [5 6]
 [2 3]
 [0 1]]


array([[3, 4],
       [5, 6],
       [2, 3],
       [0, 1]])

Now we're ready to define the `net_face_flux_at_cells` method. This is one of a series of similar methods. We assume the caller has given us an array of length NF (number of faces) containing flux per unit face width. The first step is to convert this to total flux by multiplying by face width.

Then, for each node, we want to add up the incoming fluxes and subtract the outgoing fluxes. The algorithm does this by iterating over the 4 cardinal directions. In the first iteration, we take the IDs of all nodes' east links (which is row 0 of `links_at_node`. The flux corresponding to these links is `total_flux[links_at_node[0]]`.

Wait a minute, I thought we wanted faces, not links? We do, but here's the thing: every face has a corresponding link. We simply need to find those links corresponding to the faces. 

What if there is no east link at a particular node? Then its entry in `links_at_node` will be -1, which means it will take the value of the last entry in the flux array. That's the wrong flux value, of course, but it does not matter: we multiply each link flux by the corresponding entry in `link_dirs_at_node`. If there is no such link, this value is zero---so whatever 

In [154]:
def net_face_flux_at_cells(grid, unit_flux_at_faces):
    total_flux = unit_flux_at_faces * grid.face_width
    nffc = np.zeros(grid.number_of_cells)
    for r in range(4):
        nffc += total_flux[grid.gt_faces_at_cell[r,:]] \
        * grid.gt_link_dirs_at_node[r,grid.node_at_cell]
    return nffc

We also seem to be missing a `face_width` property, so we'll create that under the assumption node spacing is uniform:

In [155]:
rg.face_width = rg._dx

Now we should have everything needed to run the `net_face_flux_at_cells` function. It ought to return an array with the following values: 

At cell 0, we have fluxes of: -14 (east), -50 (north), -50 (west), -50 (south), which sums to -164.

At cell 1, we have fluxes of: -36 (east), -36 (north), +14 (west), -36 (south), which sums to -94.

In [156]:
net_face_flux_at_cells(rg, unit_flux_at_faces)

array([-164.,  -94.])

### Net active face fluxes at cells

If we wanted to work just with active links (treating closed boundaries as walls), we would instead use `unit_flux_at_active_faces`. In this case, with the east and north sides closed, we should get:

cell 0: -14 (east) + 0 (north) - 50 (west) - 50 (south) = -114

cell 1: 0 (east) + 0 (north) + 14 (west) - 36 (south) = -22

In [157]:
net_face_flux_at_cells(rg, unit_flux_at_active_faces)

array([-114.,  -22.])

### Face flux divergence at cells

Let's pause for some definitions:

Let *unit flux*, $q$, be defined as the flow of mass, volume, energy, momentum, etc., per unit time per unit face width. For example, if we're working with volume fluxes, $q$ has dimensions of length squared per time. When defined at a link, it is positive in the direction of the link; when defined at a face, it is positive in the direction of the associated link.

*Total flux,* $Q$, is then simply $Q = q W$, where $W$ is the width of a face.

*Flux divergence*, $\nabla q$, at a cell is defined as $\nabla q = -\Sigma Q / A_c$, where $\Sigma$ represents a summation over all the cell's faces (or active faces, as the case may be), and $A_c$ is the surface area of the cell. Notice that if $q$ has dimensions of $L^2/T$, then $\nabla q$ has dimensions of $L/T$.

The minus sign on flux divergence keeps us consistent with standard mathematical usage. 

So, to find flux divergence at cells, we simply find the total flux and divide by the cell area (and multiply by -1). Here's a function to do this:

In [158]:
def face_flux_divergence_at_cells(grid, unit_flux_at_faces):
    return -net_face_flux_at_cells(grid, unit_flux_at_faces) / grid.area_of_cell

In the following example, the result should be 1.64 at cell 0 and 0.94 at cell 1:

In [159]:
face_flux_divergence_at_cells(rg, unit_flux_at_faces)

array([ 1.64,  0.94])

### Active face flux divergence at cells

This is the same as "all face" flux divergence, except we use a unit flux array that has zeros at the inactive faces. The answer should be 1.14 at cell zero, and 0.22 at cell 1:

In [160]:
face_flux_divergence_at_cells(rg, unit_flux_at_active_faces)

array([ 1.14,  0.22])

## Diffusion model: raster grid, fluxes at faces, divergence at cells

So now we'll test out using these algorithms repeatedly in a diffusion calculation. Same grid, same initial conditions.

In [161]:
D = 0.01
niter = 10000
dt = 0.0001  # way tinier than it needs to be, just for performance testing

In [162]:
import time
print(z)
start_time = time.time()
for i in range(10000):
    g = calculate_gradients_at_faces(rg, z)
    q = -g
    dq = face_flux_divergence_at_cells(rg, q)
    z[rg.node_at_cell] -= dq*dt
end_time = time.time()
print(z)
print(1000*(end_time-start_time)/niter)

[  0.   0.   0.   0.   0.  50.  36.   0.   0.   0.   0.   0.]
[  0.           0.           0.           0.           0.          48.3877612
  35.07055093   0.           0.           0.           0.           0.        ]
0.0916630983353


Last time I ran this it took about 0.07 ms per iteration. For completeness, we'll try an active-face version:

In [163]:
z[5] = 50.
z[6] = 36.
import time
start_time = time.time()
q = rg.zeros(centering='face')
fal = rg.face_at_link  # would be easier if this were a property
af = fal[rg.active_links]  # we apparently don't have active_faces
for i in range(niter):
    g = calculate_gradients_at_faces(rg, z)
    q[af] = -g[af]
    dq = face_flux_divergence_at_cells(rg, q)
    z[rg.node_at_cell] -= dq*dt
end_time = time.time()
print(z)
print(1000*(end_time-start_time)/niter)

[  0.           0.           0.           0.           0.          48.87582825
  35.77657619   0.           0.           0.           0.           0.        ]
0.0686928987503


So, based on the last time I ran this example, the two versions have about the same speed.

# Hex grid examples: faces and cells

This next section repeats the previous one but for a hex grid (as an example of a Voronoi).

In [164]:
from landlab import HexModelGrid

In [165]:
hg = HexModelGrid(3, 3, 10.0)
z = rg.add_zeros('node', 'topographic__elevation')
z[4] = 50.
z[5] = 36.
rg.set_closed_nodes([6, 7, 8, 9])
print(z)

[  0.   0.   0.   0.  50.  36.   0.   0.   0.   0.   0.   0.]


The first problem we encounter is that for generic grids, unlike raster grids, `link_at_face` is a property rather than plain method (i.e., it's a method with a @property tag). We can fix this by redefining the gradient function slightly.

Once that's fixed, we can test the gradient function. The gradients should be:

`[5, 5, 3.6, 3.6, 5, -1.4, -3.6, -5, -5, -3.6, -3.6]`

In [166]:
    def gt_setup_link_and_face_temp(grid):
        """Set up link_at_face and face_at_link arrays.
        """
        from landlab import BAD_INDEX_VALUE
        grid._face_at_link = np.zeros(grid.number_of_links, dtype=int)
        grid._face_at_link[:] = BAD_INDEX_VALUE
        grid._num_faces = len(grid.face_width)
        grid._link_at_face = np.zeros(grid._num_faces, dtype=int)
        face_id = 0
        for link in range(grid.number_of_links):
            tc = grid.cell_at_node[grid.node_at_link_tail[link]]
            hc = grid.cell_at_node[grid.node_at_link_head[link]]
            if tc != BAD_INDEX_VALUE or hc != BAD_INDEX_VALUE:
                grid._face_at_link[link] = face_id
                grid._link_at_face[face_id] = link
                face_id += 1

In [167]:
gt_setup_link_and_face_temp(hg)

In [168]:
g = calculate_gradients_at_faces(hg, z)
g

array([ 5. ,  5. ,  3.6,  3.6,  5. , -1.4, -3.6, -5. , -5. , -3.6, -3.6])

In [169]:
hg.set_closed_nodes([6, 7, 8, 9])

In [170]:
unit_flux_at_faces = -g
unit_flux_at_faces

array([-5. , -5. , -3.6, -3.6, -5. ,  1.4,  3.6,  5. ,  5. ,  3.6,  3.6])

### Net face fluxes at cells

Again, we'll need `links_at_node` and `faces_at_cell`, this time for a Voronoi grid. To make these, we need to know the maximum number of links at each node. Here's a function to do this.

In [171]:
def find_number_of_links_per_node(grid):
    """Find and record how many links are attached to each node."""
    grid._number_of_links_per_node = np.zeros(grid.number_of_nodes, dtype=np.int)
    for ln in range(grid.number_of_links):
        grid._number_of_links_per_node[grid.node_at_link_tail[ln]] += 1
        grid._number_of_links_per_node[grid.node_at_link_head[ln]] += 1

In [172]:
# when made a member of grid, should be a property
def number_of_links_per_node(grid):
    try:
        return grid._number_of_links_per_node
    except AttributeError:
        find_number_of_links_per_node(grid)
        return grid._number_of_links_per_node

In [173]:
nlpn = number_of_links_per_node(hg)
nlpn

array([3, 4, 3, 3, 6, 6, 3, 3, 4, 3])

In [174]:
def make_links_at_node_array_general(grid):
    """Make array with links at each node
    """
    # Find maximum number of links per node
    nlpn = number_of_links_per_node(grid)   #this fn should become member and property
    max_num_links = np.amax(nlpn)
    nlpn[:] = 0  # we'll zero it out, then rebuild it

    #for later examples:
    # nlpn should be [3 4 3 3 6 6 3 3 4 3] and max should be 6
    
    # Create arrays for link-at-node information
    grid.gt_links_at_node = -np.ones((max_num_links, grid.number_of_nodes), dtype=np.int32)
    grid.gt_link_dirs_at_node = np.zeros((max_num_links, grid.number_of_nodes), dtype=np.int8)
    grid.gt_active_link_dirs_at_node = np.zeros((max_num_links, grid.number_of_nodes), dtype=np.int8)
    grid.gt_num_active_links_at_node = np.zeros(grid.number_of_nodes, dtype=np.uint8)  # assume <256 links at any node

    # Sweep over all links
    for lk in xrange(grid.number_of_links):

        # Find the IDs of the tail and head nodes
        t = grid.node_at_link_tail[lk]
        h = grid.node_at_link_head[lk]

        # Add this link to the list for this node, set the direction (outgoing,
        # indicated by -1), and increment the number found so far
        grid.gt_links_at_node[nlpn[t]][t] = lk
        grid.gt_links_at_node[nlpn[h]][h] = lk
        grid.gt_link_dirs_at_node[nlpn[t]][t] = -1
        grid.gt_link_dirs_at_node[nlpn[h]][h] = 1
        nlpn[t] += 1
        nlpn[h] += 1

In [175]:
make_links_at_node_array_general(hg)
hg.gt_links_at_node

array([[ 0,  0,  1,  2,  3,  5,  7, 11, 13, 15],
       [ 2,  1,  6,  8,  4,  6, 10, 12, 14, 16],
       [ 3,  4,  7, 11,  8,  9, 16, 17, 17, 18],
       [-1,  5, -1, -1,  9, 10, -1, -1, 18, -1],
       [-1, -1, -1, -1, 12, 14, -1, -1, -1, -1],
       [-1, -1, -1, -1, 13, 15, -1, -1, -1, -1]], dtype=int32)

In [176]:
hg.gt_link_dirs_at_node

array([[-1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1,  1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1,  1,  1, -1, -1,  1,  1],
       [ 0, -1,  0,  0, -1, -1,  0,  0, -1,  0],
       [ 0,  0,  0,  0, -1, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1, -1,  0,  0,  0,  0]], dtype=int8)

In [177]:
hg.number_of_links

19

### Sorting node links (and ultimately neighbors) by angle
We would ideally like to have `link_at_node`, `link_dir_at_node`, and `neighbor_at_node` (and any others like this) sorted in counter-clockwise order starting from "horizontal" (positive *x* axis). This section assembles the ingredients for this.

In [178]:
# The numpy arctan2 function tells us the angle of a ray from origin to given point(s)
x = np.array([1.0, 3.0*3.0**0.5, 1.0, 3.0, 0.0])
y = np.array([0.0, 3.0, 1.0, 3.0*3.0**0.5, 1.0])
ang = np.arctan2(-y, x)
180*ang/np.pi

array([ -0., -30., -45., -60., -90.])

In [189]:
def link_angle(grid, links, dirs):
    """Find and return the angle of link(s) in given direction.
    
    Parameters
    ----------
    grid : ModelGrid object
        reference to the grid
    links : 1d numpy array
        one or more link IDs
    dirs : 1d numpy array (must be same length as links)
        direction of links relative to node: +1 means head is origin;
        -1 means tail is origin.
    
    Notes
    -----
    dx and dy are the x and y differences between the link endpoints. 
    Multiplying this by dirs orients these offsets correctly (i.e.,
    the correct node is the origin). The call to arctan2 calculates
    the angle in radians. Angles in the lower two quadrants will be
    negative and clockwise from the positive x axis. We want them
    counter-clockwise, which is what the last couple of lines before
    the return statement do.
    """
    dx = -dirs * (grid.node_x[grid.node_at_link_head[links]] - grid.node_x[grid.node_at_link_tail[links]])
    dy = -dirs * (grid.node_y[grid.node_at_link_head[links]] - grid.node_y[grid.node_at_link_tail[links]])
    ang = np.arctan2(dy, dx)
    (lower_two_quads, ) = np.where(ang<0.0)
    ang[lower_two_quads] = (2 * np.pi) + ang[lower_two_quads]
    (no_link, ) = np.where(dirs == 0)
    ang[no_link] = 2*np.pi
    return ang

Test 1: for node 4 of our 3x3 hex grid, there should be 6 links with angles 240, 300, 180, 0, 120, and 60 degrees.

In [190]:
180*link_angle(hg, hg.gt_links_at_node[:,4], hg.gt_link_dirs_at_node[:,4]) / np.pi

array([ 240.,  300.,  180.,    0.,  120.,   60.])

Test 2: angle should be $2\pi$ where there is no link (indicated by dir==0). This serves to force no-link entries to the end of the array.

In [192]:
180*link_angle(hg, hg.gt_links_at_node[:,6], hg.gt_link_dirs_at_node[:,6]) / np.pi

array([ 240.,  180.,  120.,  360.,  360.,  360.])

### Sorting links at node by link angle

In [195]:
def sort_links_at_node_by_angle(grid):
    """Sort the links_at_node and link_dirs_at_node arrays by angle.
    """
    for n in range(grid.number_of_nodes):
        ang = link_angle(grid, grid.gt_links_at_node[:,n], grid.gt_link_dirs_at_node[:,n])
        indices = np.argsort(ang)
        grid.gt_links_at_node[:,n] = grid.gt_links_at_node[indices,n]
        grid.gt_link_dirs_at_node[:,n] = grid.gt_link_dirs_at_node[indices,n]

Test: our (3, 3) hex grid should now have links_at_node that looks like this:

`array([[ 0,  1,  7,  8,  9, 10, 16, 17, 18, 18],
       [ 3,  5,  6, 11, 13, 15, 10, 11, 17, 15],
       [ 2,  4,  1,  2, 12, 14,  7, 12, 13, 16],
       [-1,  0, -1, -1,  8,  9, -1, -1, 14, -1],
       [-1, -1, -1, -1,  3,  5, -1, -1, -1, -1],
       [-1, -1, -1, -1,  4,  6, -1, -1, -1, -1]], dtype=int32)`

In [197]:
hg.gt_links_at_node

array([[ 0,  1,  7,  8,  9, 10, 16, 17, 18, 18],
       [ 3,  5,  6, 11, 13, 15, 10, 11, 17, 15],
       [ 2,  4,  1,  2, 12, 14,  7, 12, 13, 16],
       [-1,  0, -1, -1,  8,  9, -1, -1, 14, -1],
       [-1, -1, -1, -1,  3,  5, -1, -1, -1, -1],
       [-1, -1, -1, -1,  4,  6, -1, -1, -1, -1]], dtype=int32)

Link directions should look like this:

`array([[-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1, -1,  1,  1,  1,  1],
       [-1, -1,  1,  1, -1, -1,  1,  1,  1,  1],
       [ 0,  1,  0,  0,  1,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  1,  0,  0,  0,  0]], dtype=int8)`

In [198]:
hg.gt_link_dirs_at_node

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
       [-1, -1, -1, -1, -1, -1,  1,  1,  1,  1],
       [-1, -1,  1,  1, -1, -1,  1,  1,  1,  1],
       [ 0,  1,  0,  0,  1,  1,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  1,  0,  0,  0,  0]], dtype=int8)